# Generated by Django 5.0.6 on 2024-06-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="tags",
        ),
        migrations.AddField(
            model_name="program",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Adult", "Adult"),
                    ("Animated", "Animated"),
                    ("Casting", "Casting"),
                    ("Children", "Children"),
                    ("Comedy", "Comedy"),
                    ("Cooking", "Cooking"),
                    ("Court", "Court"),
                    ("Debate", "Debate"),
                    ("Documentary", "Documentary"),
                    ("Drama", "Drama"),
                    ("Educational", "Educational"),
                    ("Ethnofiction/Cultural", "Ethnofiction/Cultural"),
                    ("Entertainment", "Entertainment"),
                    ("Fantasy", "Fantasy"),
                    ("Food reality (culinary)", "Food reality (culinary)"),
                    ("Game", "Game"),
                    ("Generalist", "Generalist"),
                    ("Mythological", "Mythological"),
                    ("Hidden camera", "Hidden camera"),
                    ("Historical", "Historical"),
                    ("Interview", "Interview"),
                    ("Late-night", "Late-night"),
                    ("Medical", "Medical"),
                    ("Micro-series", "Micro-series"),
                    ("Mockumentary", "Mockumentary"),
                    ("Music", "Music"),
                    ("Movie", "Movie"),
                    ("News magazine", "News magazine"),
                    ("Political", "Political"),
                    ("Psychological", "Psychological"),
                    ("Public affairs", "Public affairs"),
                    ("Media", "Media"),
                    ("Reality", "Reality"),
                    ("Science & Technology", "Science & Technology"),
                    ("Serial", "Serial"),
                    ("Sketch comedy", "Sketch comedy"),
                    ("Specialty", "Specialty"),
                    ("Student", "Student"),
                    ("Talk show", "Talk show"),
                    ("Teen sitcom", "Teen sitcom"),
                    ("Thriller", "Thriller"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
