# Generated by Django 5.0.6 on 2024-06-05 06:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0003_program_description_programs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="programs",
            unique_together={("user", "program")},
        ),
    ]
