# Generated by Django 5.0.6 on 2024-06-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0004_alter_programs_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
