# Generated by Django 5.0.6 on 2024-06-05 21:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0005_program_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Programs",
            new_name="UserPrograms",
        ),
    ]
