# Generated by Django 5.0.6 on 2024-06-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0006_rename_programs_userprograms"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="thumbnail",
            field=models.FileField(null=True, upload_to="uploads/"),
        ),
    ]
