# Generated by Django 5.0.6 on 2024-06-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0007_program_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="thumbnail",
            field=models.FileField(
                default="programs/static/uploads/default_thumbnail.jpg",
                upload_to="programs/static/uploads/",
            ),
        ),
    ]
